// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dashboard.proto

// Protobuf Java Version: 3.25.3
package stats.service.dashboard;

public final class DashboardProto {
  private DashboardProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stats_service_dashboard_UserPredictionsRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stats_service_dashboard_UserPredictionsRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stats_service_dashboard_SimilarEventsRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stats_service_dashboard_SimilarEventsRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stats_service_dashboard_InteractionsCountRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stats_service_dashboard_InteractionsCountRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stats_service_dashboard_RecommendedEventProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stats_service_dashboard_RecommendedEventProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017dashboard.proto\022\027stats.service.dashboa" +
      "rd\"C\n\033UserPredictionsRequestProto\022\017\n\007use" +
      "r_id\030\001 \001(\003\022\023\n\013max_results\030\002 \001(\005\"S\n\031Simil" +
      "arEventsRequestProto\022\020\n\010event_id\030\001 \001(\003\022\017" +
      "\n\007user_id\030\002 \001(\003\022\023\n\013max_results\030\003 \001(\005\"1\n\035" +
      "InteractionsCountRequestProto\022\020\n\010event_i" +
      "d\030\001 \003(\003\"8\n\025RecommendedEventProto\022\020\n\010even" +
      "t_id\030\001 \001(\003\022\r\n\005score\030\002 \001(\0012\236\003\n\031Recommenda" +
      "tionsController\022\203\001\n\031GetRecommendationsFo" +
      "rUser\0224.stats.service.dashboard.UserPred" +
      "ictionsRequestProto\032..stats.service.dash" +
      "board.RecommendedEventProto0\001\022x\n\020GetSimi" +
      "larEvents\0222.stats.service.dashboard.Simi" +
      "larEventsRequestProto\032..stats.service.da" +
      "shboard.RecommendedEventProto0\001\022\200\001\n\024GetI" +
      "nteractionsCount\0226.stats.service.dashboa" +
      "rd.InteractionsCountRequestProto\032..stats" +
      ".service.dashboard.RecommendedEventProto" +
      "0\001B\022B\016DashboardProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_stats_service_dashboard_UserPredictionsRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stats_service_dashboard_UserPredictionsRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stats_service_dashboard_UserPredictionsRequestProto_descriptor,
        new java.lang.String[] { "UserId", "MaxResults", });
    internal_static_stats_service_dashboard_SimilarEventsRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_stats_service_dashboard_SimilarEventsRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stats_service_dashboard_SimilarEventsRequestProto_descriptor,
        new java.lang.String[] { "EventId", "UserId", "MaxResults", });
    internal_static_stats_service_dashboard_InteractionsCountRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_stats_service_dashboard_InteractionsCountRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stats_service_dashboard_InteractionsCountRequestProto_descriptor,
        new java.lang.String[] { "EventId", });
    internal_static_stats_service_dashboard_RecommendedEventProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_stats_service_dashboard_RecommendedEventProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stats_service_dashboard_RecommendedEventProto_descriptor,
        new java.lang.String[] { "EventId", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
