// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dashboard.proto

// Protobuf Java Version: 3.25.3
package stats.service.dashboard;

public interface InteractionsCountRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stats.service.dashboard.InteractionsCountRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 event_id = 1;</code>
   * @return A list containing the eventId.
   */
  java.util.List<java.lang.Long> getEventIdList();
  /**
   * <code>repeated int64 event_id = 1;</code>
   * @return The count of eventId.
   */
  int getEventIdCount();
  /**
   * <code>repeated int64 event_id = 1;</code>
   * @param index The index of the element to return.
   * @return The eventId at the given index.
   */
  long getEventId(int index);
}
