// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dashboard.proto

// Protobuf Java Version: 3.25.3
package stats.service.dashboard;

/**
 * Protobuf type {@code stats.service.dashboard.InteractionsCountRequestProto}
 */
public final class InteractionsCountRequestProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:stats.service.dashboard.InteractionsCountRequestProto)
    InteractionsCountRequestProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InteractionsCountRequestProto.newBuilder() to construct.
  private InteractionsCountRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InteractionsCountRequestProto() {
    eventId_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InteractionsCountRequestProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return stats.service.dashboard.DashboardProto.internal_static_stats_service_dashboard_InteractionsCountRequestProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return stats.service.dashboard.DashboardProto.internal_static_stats_service_dashboard_InteractionsCountRequestProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            stats.service.dashboard.InteractionsCountRequestProto.class, stats.service.dashboard.InteractionsCountRequestProto.Builder.class);
  }

  public static final int EVENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList eventId_ =
      emptyLongList();
  /**
   * <code>repeated int64 event_id = 1;</code>
   * @return A list containing the eventId.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getEventIdList() {
    return eventId_;
  }
  /**
   * <code>repeated int64 event_id = 1;</code>
   * @return The count of eventId.
   */
  public int getEventIdCount() {
    return eventId_.size();
  }
  /**
   * <code>repeated int64 event_id = 1;</code>
   * @param index The index of the element to return.
   * @return The eventId at the given index.
   */
  public long getEventId(int index) {
    return eventId_.getLong(index);
  }
  private int eventIdMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getEventIdList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(eventIdMemoizedSerializedSize);
    }
    for (int i = 0; i < eventId_.size(); i++) {
      output.writeInt64NoTag(eventId_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < eventId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(eventId_.getLong(i));
      }
      size += dataSize;
      if (!getEventIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      eventIdMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof stats.service.dashboard.InteractionsCountRequestProto)) {
      return super.equals(obj);
    }
    stats.service.dashboard.InteractionsCountRequestProto other = (stats.service.dashboard.InteractionsCountRequestProto) obj;

    if (!getEventIdList()
        .equals(other.getEventIdList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEventIdCount() > 0) {
      hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEventIdList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static stats.service.dashboard.InteractionsCountRequestProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static stats.service.dashboard.InteractionsCountRequestProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static stats.service.dashboard.InteractionsCountRequestProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(stats.service.dashboard.InteractionsCountRequestProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code stats.service.dashboard.InteractionsCountRequestProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:stats.service.dashboard.InteractionsCountRequestProto)
      stats.service.dashboard.InteractionsCountRequestProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stats.service.dashboard.DashboardProto.internal_static_stats_service_dashboard_InteractionsCountRequestProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stats.service.dashboard.DashboardProto.internal_static_stats_service_dashboard_InteractionsCountRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stats.service.dashboard.InteractionsCountRequestProto.class, stats.service.dashboard.InteractionsCountRequestProto.Builder.class);
    }

    // Construct using stats.service.dashboard.InteractionsCountRequestProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventId_ = emptyLongList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return stats.service.dashboard.DashboardProto.internal_static_stats_service_dashboard_InteractionsCountRequestProto_descriptor;
    }

    @java.lang.Override
    public stats.service.dashboard.InteractionsCountRequestProto getDefaultInstanceForType() {
      return stats.service.dashboard.InteractionsCountRequestProto.getDefaultInstance();
    }

    @java.lang.Override
    public stats.service.dashboard.InteractionsCountRequestProto build() {
      stats.service.dashboard.InteractionsCountRequestProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public stats.service.dashboard.InteractionsCountRequestProto buildPartial() {
      stats.service.dashboard.InteractionsCountRequestProto result = new stats.service.dashboard.InteractionsCountRequestProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(stats.service.dashboard.InteractionsCountRequestProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        eventId_.makeImmutable();
        result.eventId_ = eventId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof stats.service.dashboard.InteractionsCountRequestProto) {
        return mergeFrom((stats.service.dashboard.InteractionsCountRequestProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(stats.service.dashboard.InteractionsCountRequestProto other) {
      if (other == stats.service.dashboard.InteractionsCountRequestProto.getDefaultInstance()) return this;
      if (!other.eventId_.isEmpty()) {
        if (eventId_.isEmpty()) {
          eventId_ = other.eventId_;
          eventId_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureEventIdIsMutable();
          eventId_.addAll(other.eventId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              long v = input.readInt64();
              ensureEventIdIsMutable();
              eventId_.addLong(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureEventIdIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                eventId_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList eventId_ = emptyLongList();
    private void ensureEventIdIsMutable() {
      if (!eventId_.isModifiable()) {
        eventId_ = makeMutableCopy(eventId_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated int64 event_id = 1;</code>
     * @return A list containing the eventId.
     */
    public java.util.List<java.lang.Long>
        getEventIdList() {
      eventId_.makeImmutable();
      return eventId_;
    }
    /**
     * <code>repeated int64 event_id = 1;</code>
     * @return The count of eventId.
     */
    public int getEventIdCount() {
      return eventId_.size();
    }
    /**
     * <code>repeated int64 event_id = 1;</code>
     * @param index The index of the element to return.
     * @return The eventId at the given index.
     */
    public long getEventId(int index) {
      return eventId_.getLong(index);
    }
    /**
     * <code>repeated int64 event_id = 1;</code>
     * @param index The index to set the value at.
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        int index, long value) {

      ensureEventIdIsMutable();
      eventId_.setLong(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 event_id = 1;</code>
     * @param value The eventId to add.
     * @return This builder for chaining.
     */
    public Builder addEventId(long value) {

      ensureEventIdIsMutable();
      eventId_.addLong(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 event_id = 1;</code>
     * @param values The eventId to add.
     * @return This builder for chaining.
     */
    public Builder addAllEventId(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureEventIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, eventId_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      eventId_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:stats.service.dashboard.InteractionsCountRequestProto)
  }

  // @@protoc_insertion_point(class_scope:stats.service.dashboard.InteractionsCountRequestProto)
  private static final stats.service.dashboard.InteractionsCountRequestProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new stats.service.dashboard.InteractionsCountRequestProto();
  }

  public static stats.service.dashboard.InteractionsCountRequestProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InteractionsCountRequestProto>
      PARSER = new com.google.protobuf.AbstractParser<InteractionsCountRequestProto>() {
    @java.lang.Override
    public InteractionsCountRequestProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InteractionsCountRequestProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InteractionsCountRequestProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public stats.service.dashboard.InteractionsCountRequestProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

