// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dashboard.proto

// Protobuf Java Version: 3.25.3
package stats.service.dashboard;

public interface RecommendedEventProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stats.service.dashboard.RecommendedEventProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 event_id = 1;</code>
   * @return The eventId.
   */
  long getEventId();

  /**
   * <code>double score = 2;</code>
   * @return The score.
   */
  double getScore();
}
