// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dashboard.proto

// Protobuf Java Version: 3.25.3
package stats.service.dashboard;

public interface SimilarEventsRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stats.service.dashboard.SimilarEventsRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 event_id = 1;</code>
   * @return The eventId.
   */
  long getEventId();

  /**
   * <code>int64 user_id = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int32 max_results = 3;</code>
   * @return The maxResults.
   */
  int getMaxResults();
}
