// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

// Protobuf Java Version: 3.25.3
package stats.service.collector;

/**
 * Protobuf enum {@code stats.service.collector.ActionTypeProto}
 */
public enum ActionTypeProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ACTION_VIEW = 0;</code>
   */
  ACTION_VIEW(0),
  /**
   * <code>ACTION_REGISTER = 1;</code>
   */
  ACTION_REGISTER(1),
  /**
   * <code>ACTION_LIKE = 2;</code>
   */
  ACTION_LIKE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ACTION_VIEW = 0;</code>
   */
  public static final int ACTION_VIEW_VALUE = 0;
  /**
   * <code>ACTION_REGISTER = 1;</code>
   */
  public static final int ACTION_REGISTER_VALUE = 1;
  /**
   * <code>ACTION_LIKE = 2;</code>
   */
  public static final int ACTION_LIKE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ActionTypeProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ActionTypeProto forNumber(int value) {
    switch (value) {
      case 0: return ACTION_VIEW;
      case 1: return ACTION_REGISTER;
      case 2: return ACTION_LIKE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ActionTypeProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ActionTypeProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ActionTypeProto>() {
          public ActionTypeProto findValueByNumber(int number) {
            return ActionTypeProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return stats.service.collector.CollectorProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ActionTypeProto[] VALUES = values();

  public static ActionTypeProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ActionTypeProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:stats.service.collector.ActionTypeProto)
}

