// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

// Protobuf Java Version: 3.25.3
package stats.service.collector;

public final class CollectorProto {
  private CollectorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_stats_service_collector_UserActionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_stats_service_collector_UserActionProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017collector.proto\022\027stats.service.collect" +
      "or\032\033google/protobuf/empty.proto\032\037google/" +
      "protobuf/timestamp.proto\"\242\001\n\017UserActionP" +
      "roto\022\017\n\007user_id\030\001 \001(\003\022\020\n\010event_id\030\002 \001(\003\022" +
      "=\n\013action_type\030\003 \001(\0162(.stats.service.col" +
      "lector.ActionTypeProto\022-\n\ttimestamp\030\004 \001(" +
      "\0132\032.google.protobuf.Timestamp*H\n\017ActionT" +
      "ypeProto\022\017\n\013ACTION_VIEW\020\000\022\023\n\017ACTION_REGI" +
      "STER\020\001\022\017\n\013ACTION_LIKE\020\0022m\n\024UserActionCon" +
      "troller\022U\n\021CollectUserAction\022(.stats.ser" +
      "vice.collector.UserActionProto\032\026.google." +
      "protobuf.EmptyB\022B\016CollectorProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_stats_service_collector_UserActionProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_stats_service_collector_UserActionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_stats_service_collector_UserActionProto_descriptor,
        new java.lang.String[] { "UserId", "EventId", "ActionType", "Timestamp", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
