// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector.proto

// Protobuf Java Version: 3.25.3
package stats.service.collector;

public interface UserActionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:stats.service.collector.UserActionProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 event_id = 2;</code>
   * @return The eventId.
   */
  long getEventId();

  /**
   * <code>.stats.service.collector.ActionTypeProto action_type = 3;</code>
   * @return The enum numeric value on the wire for actionType.
   */
  int getActionTypeValue();
  /**
   * <code>.stats.service.collector.ActionTypeProto action_type = 3;</code>
   * @return The actionType.
   */
  stats.service.collector.ActionTypeProto getActionType();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
