server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: main-service-api
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/admin/**,/users/**,/categories/**,/compilations/**,/events/**
